# Generated by Django 2.2.19 on 2022-01-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_auto_20220124_1729"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredient_to_recipe",
                to="recipes.Recipe",
            ),
        ),
    ]
